services:
  - type: web
    name: collavo
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildArgs:
      VITE_GOOGLE_MAPS_API_KEY: <REPLACE_WITH_YOUR_MAPS_KEY>
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SEED_DEMO
        value: "true"
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        value: https://collavo.onrender.com
      - key: ADMIN_CLIENT_ORIGIN
        value: https://collavo.onrender.com
      - key: ADMIN_ROUTE_PATH
        value: ops-9f3k2
      - key: AZURE_BLOB_CONNECTION_STRING
        sync: false
      - key: AZURE_BLOB_PRIVATE_CONTAINER
        value: collavo-private
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://collavo.onrender.com/api/auth/google/callback
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-flash-lite-latest
